2015-12-11 16:18:55,020 export.safeKeep CRITICAL MultiUserExperience data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:18:57,822 export.safeKeep CRITICAL CC data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:18:59,823 export.safeKeep CRITICAL BBSIQ data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:01,329 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:01,370 export.safeKeep CRITICAL DASS21_DS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:02,616 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:02,662 export.safeKeep CRITICAL QOL data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:04,410 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:04,880 export.safeKeep CRITICAL OA data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:06,261 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:06,329 export.safeKeep CRITICAL RR data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:08,241 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:08,306 export.safeKeep CRITICAL ImpactAnxiousImagery data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:09,652 export.safeKeep CRITICAL SUDS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:10,933 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:11,167 export.safeKeep CRITICAL AnxietyTriggers data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:12,781 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:12,845 export.safeKeep CRITICAL DD data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:14,123 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:14,201 export.safeKeep CRITICAL Credibility data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:15,940 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:16,030 export.safeKeep CRITICAL MentalHealthHxTx data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:17,830 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:17,883 export.safeKeep CRITICAL ImageryPrime data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:19,636 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:19:19,691 export.safeKeep CRITICAL ReasonsForEnding data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:21,072 export.safeKeep CRITICAL Demographic data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:22,459 export.safeKeep CRITICAL CIHS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:24,223 export.safeKeep CRITICAL DASS21_AS data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:19:25,612 export.safeKeep CRITICAL DD_FU data backup failed, immediate attention needed.
Traceback (most recent call last):
  File "export.py", line 66, in safeKeep
    db = shelve.open(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (2, 'No such file or directory')
2015-12-11 16:20:40,936 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,032 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,175 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,418 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,553 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,692 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,839 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:41,938 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:42,051 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:42,327 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:20:42,414 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,486 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,574 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,693 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:44,923 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,077 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,221 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,355 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,445 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,526 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,734 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:22:45,817 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:03,636 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:03,712 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:03,816 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,025 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,173 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,405 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,551 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,644 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,729 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,905 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:23:04,973 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,020 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,101 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,256 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,483 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,626 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,783 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:00,926 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,009 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,101 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,316 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 16:32:01,393 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:48,199 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = BBSIQ, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:49,450 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DASS21_DS, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:50,640 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = QOL, Entry ID: 28, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:50,875 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:51,844 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = RR, Entry ID: 25, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:54,747 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = SUDS, Entry ID: 43, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:55,373 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = AnxietyTriggers, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:55,934 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = DD, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:56,531 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = Credibility, Entry ID: 21, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:20:56,829 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 98, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/1
2015-12-11 17:21:03,552 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 98, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/2
2015-12-11 17:21:14,436 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = MentalHealthHxTx, Entry ID: 24, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:21:15,671 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = ImageryPrime, Entry ID: 36, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:31:20,309 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:31:20,638 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/1
2015-12-11 17:31:23,552 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/2
2015-12-11 17:31:35,463 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:31:35,819 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/1
2015-12-11 17:31:37,010 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/2
2015-12-11 17:31:41,910 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:31:42,229 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/1
2015-12-11 17:31:43,610 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/2
2015-12-11 17:41:07,813 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:41:08,172 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/1
2015-12-11 17:41:11,206 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/2
2015-12-11 17:45:59,559 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 48, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
2015-12-11 17:45:59,890 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/1
2015-12-11 17:46:02,196 export.safeDelete CRITICAL Data delete failed, fatal, emailed admin. see below for error information:
Traceback (most recent call last):
  File "export.py", line 100, in safeDelete
    m = delete.raise_for_status()
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/api/export/MentalHealthHxTx/2
2015-12-11 17:52:46,395 export.decrypt  ERROR    Decode failed, item skipped. Questionnaire = OA, Entry ID: 49, Field: participantRSA See information:
Traceback (most recent call last):
  File "export.py", line 53, in decrypt
    value = crypto.decode('base64')
  File "/Users/Diheng/PIExporter/venv/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
